# Site settings
title: Alexander Bergholm
email: bergholm.alexander@gmail.com
url: https://bergholmalexander.github.io
description: "Resume/Website for Alexander Bergholm, an undergraduate researcher at UBC striving to learn more about machine learning in healthcare."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: bergholmalexander.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/PLAIbergholm
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/bergholmalexander

# Build settings
markdown: kramdown
permalink: pretty
